name: Jobs API CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
  ## set CI env variable to true to disable watch mode on npm tests 
    env:
      CI: true
      MONGO_URL: mongodb://localhost/jobs-api
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version !{{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.6.0
        with: 
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: supercharge
          mongodb-password: secret
          mongodb-db: supercharge
      - run: npm install     
      - run: npm test